In [3]:
import numpy as np

In [4]:
#a)
    # Definir las matrices
S = np.array([1, 0, 1])
    # Calcular la norma al cuadrado de la matriz
SS = np.dot(S.T, S)
SS = np.squeeze(SS)
SS = np.round(SS, 4)

print("El cuadrado del desplazamiento es:", SS)


El cuadrado del desplazamiento es: 2


In [8]:
#b)
    # Definir las matrices
A = np.array([[1/np.sqrt(2), 0, 1/np.sqrt(2)],
              [0, 1, 0],
              [-1/np.sqrt(2), 0, 1/np.sqrt(2)]])

B = np.array([[1],
              [0],
              [1]])

    # Realizar la multiplicación de matrices
AB = np.dot(A, B)

print(AB)

    # Calcular la norma al cuadrado de la matriz
ABAB = np.dot(AB.T, AB)
ABAB = np.squeeze(ABAB)
ABAB = np.round(ABAB, 4)

print("El cuadrado del desplazamiento es:", ABAB)

[[1.41421356]
 [0.        ]
 [0.        ]]
El cuadrado del desplazamiento es: 2.0


In [6]:
#c)
    # Definir las matrices
AT = np.array([[1/np.sqrt(2), 0, -1/np.sqrt(2)],
              [0, 1, 0],
              [1/np.sqrt(2), 0, 1/np.sqrt(2)]])

I = np.array([[1,0,0],
              [0, 1, 0],
              [0,0,1]])

    # Realizar la multiplicación de matrices
ATI = np.dot(AT, I)
ATIA = np.dot(ATI, A)

    # Calcular la norma al cuadrado de la matriz y redondeo
ATIA = np.squeeze(ATIA)
ATIA = np.round(ATIA, 4)

print(ATIA)


[[ 1.  0. -0.]
 [ 0.  1.  0.]
 [-0.  0.  1.]]
